lecture:
  file:
    path: src/main/resources/lecture/video
article:
  file:
    path: src/main/resources/article

spring:
  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB
  mvc:
    static-path-pattern: /static/**