spring:
  profiles:
    active: prod
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: true
    defer-datasource-initialization: true
  datasource:
    url: jdbc:mysql://localhost:3307/se_project
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jwt:
    secret: nG3DuiwZjLBhoyCRmM7xnG3DuiwZjLBhoyCRmM7xnG3DuiwZjLBhoyCRmM7xnG3DuiwZjLBhoyCRmM7xnG3DuiwZjLBhoyCRmM7xnG3DuiwZjLBhoyCRmM7x
    expiration: 604800000
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  sql:
    init:
      mode: always
logging:
  level:
    root: DEBUG
    com.assignment: DEBUG


